server {
    listen 80;
    server_name nginx;

    location /stub_status {
        stub_status on;
        allow all; # 127.0.0.1;  # localhostからのアクセスを許可
        # deny all;         # 他の全てのアクセスを拒否
    }

    # 他の設定...
}