version: '3'
   
services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - grafana-data:/var/lib/grafana
     # - ./grafana_custom.ini:/etc/grafana/grafana.ini  # 新しいiniファイルをマウント
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=adminpassword  # Grafana管理者のパスワード設定
    restart: unless-stopped
    networks:  # ここでネットワークを指定
      - ecosystem

networks:
  ecosystem:
    external: true  # 既に作成されたネットワークを使用する場合
    
volumes:
  grafana-data:
    external: true