version: '3'

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.conf/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:  # ここでネットワークを指定
      - ecosystem

networks:
  ecosystem:
    external: true  # 既に作成されたネットワークを使用する場合
    